name: Kotlin CI with JaCoCo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and run tests
        run: ./gradlew build jacocoTestReport

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test

      - name: Upload code coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: build/reports/jacoco/test/html

      - name: Generate JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges

      - name: List files in badges directory (debugging)
        run: |
          ls -la .github/badges

      - name: Checkout ci-results branch and replace jacoco.svg
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          # Ensure no untracked or modified files prevent checkout
          git clean -fd || echo "No untracked files to remove"
          git reset --hard || echo "No modified files to reset"

          # Fetch the latest changes from the repository
          git fetch --all

          # Checkout ci-results branch, create it if it doesn't exist
          git checkout ci-results || git checkout -b ci-results

          # Remove the old jacoco.svg file before replacing it
          rm -f .github/badges/jacoco.svg || echo "No old jacoco.svg file to remove"

          # Add the new jacoco.svg file generated by the badge generator
          git add .github/badges/jacoco.svg
          git commit -m "Replace old jacoco.svg with new one"

          # Push the changes to the ci-results branch
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Acerik/spacex-kot-api.git ci-results --force

      - name: Merge ci-results into master
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          # Checkout master branch
          git checkout master

          # Pull latest changes from master
          git pull origin master || echo "No changes to pull"

          # Merge ci-results into master
          git merge ci-results --no-ff --no-edit

          # Push the changes to master branch
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Acerik/spacex-kot-api.git master
