name: Kotlin CI with JaCoCo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and run tests
        run: ./gradlew build jacocoTestReport

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test

      - name: Upload code coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: build/reports/jacoco/test/html

      - name: Generate JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges

      - name: Push badges to ci-results branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          # Stash any untracked changes
          git stash --include-untracked

          # Create or checkout ci-results branch
          git checkout ci-results || git checkout -b ci-results

          # Pull latest changes from remote ci-results
          git pull origin ci-results --rebase || echo "No changes to pull"

          # Apply stashed changes
          git stash pop || echo "No changes to apply"

          # Add and commit the new badge
          git add .github/badges
          git commit -m 'Add JaCoCo coverage badges' || echo "No changes to commit"

          # Push to remote ci-results branch
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Acerik/spacex-kot-api.git ci-results
      
      - name: Push code changes to master
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout master
          git pull origin master || echo "No changes to pull"
          git add .
          git commit -m 'Add code changes' || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Acerik/spacex-kot-api.git master
